#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generates Dart lookup tables from the reference vial-gui Python sources."""
import json
import os
import sys

SRC = os.path.expanduser("~/leo-code/vial-gui/src/main/python")
OUT = os.path.join(os.path.dirname(__file__), "..", "lib")
sys.path.insert(0, SRC)


# any_keycode.py imports simpleeval, which is not needed for table generation.
import types
import ast as _ast
_se = types.ModuleType("simpleeval")
_se.DEFAULT_OPERATORS = {}
def _simple_eval(expr, names=None, functions=None, operators=None):
    env = dict(names or {})
    env.update(functions or {})
    return eval(compile(_ast.parse(expr, mode="eval"), "<any_keycode>", "eval"), {"__builtins__": {}}, env)
_se.simple_eval = _simple_eval
sys.modules.setdefault("simpleeval", _se)

HEADER = (
    "// SPDX-License-Identifier: GPL-2.0-or-later\n"
    "// GENERATED by tool/gen_tables.py from vial-gui sources. Do not edit.\n\n"
)


def ds(s):
    return json.dumps(s, ensure_ascii=False).replace("$", "\\$")


def gen_kc(modname, dartname, prefix):
    import importlib
    m = getattr(importlib.import_module("keycodes." + modname), modname)
    lines = [HEADER, "const Map<String, int> %sKc = {\n" % prefix]
    for k, v in m.kc.items():
        lines.append("  %s: 0x%X,\n" % (ds(k), v))
    lines.append("};\n\n")
    lines.append("const Set<int> %sMasked = {\n" % prefix)
    for k in sorted(m.masked):
        lines.append("  0x%X,\n" % k)
    lines.append("};\n")
    with open(os.path.join(OUT, "keycodes", dartname), "w") as f:
        f.write("".join(lines))


def gen_keymaps():
    import importlib
    entries = [
        ("QWERTY", None, None),
        ("Brazilian (QWERTY)", "brazilian", "keymap"),
        ("Canadian CSA (QWERTY)", "canadian_csa", "keymap"),
        ("Colemak", "colemak", "keymap"),
        ("Colemak DH (ANSI)", "colemak_dh_ansi", "keymap"),
        ("Colemak DH (ISO)", "colemak_dh_iso", "keymap"),
        ("Colemak DH (Matrix)", "colemak_dh_matrix", "keymap"),
        ("Croatian (QWERTZ)", "croatian", "keymap"),
        ("Danish (QWERTY)", "danish", "keymap"),
        ("Dvorak", "dvorak", "keymap"),
        ("EurKey (QWERTY)", "eurkey", "keymap"),
        ("French (AZERTY)", "french", "keymap"),
        ("French (MAC)", "french", "keymap_mac"),
        ("French (BÉPO)", "french", "keymap_bepo"),
        ("German (QWERTZ)", "german", "keymap"),
        ("Hebrew (Standard)", "hebrew", "keymap"),
        ("Hungarian (QWERTZ)", "hungarian", "keymap"),
        ("Italian (QWERTY)", "italian", "keymap"),
        ("Japanese (QWERTY)", "japanese", "keymap"),
        ("Latin American (QWERTY)", "latam", "keymap"),
        ("Norwegian (QWERTY)", "norwegian", "keymap"),
        ("Portuguese (QWERTY)", "portuguese", "keymap"),
        ("Polish (QWERTY)", "polish", "keymap"),
        ("Russian (ЙЦУКЕН)", "russian", "keymap"),
        ("Slovak (QWERTY)", "slovak", "keymap"),
        ("Spanish (QWERTY)", "spanish", "keymap"),
        ("Spanish (Dvorak)", "spanish", "keymap_dvorak"),
        ("Swedish (QWERTY)", "swedish", "keymap"),
        ("Swedish (SWERTY)", "swedish_swerty", "keymap"),
        ("Swiss (QWERTZ)", "swiss", "keymap"),
        ("Turkish (QWERTY)", "turkish", "keymap"),
        ("UK (QWERTY)", "uk", "keymap"),
        ("Ukrainian (ЙЦУКЕН)", "ukrainian", "keymap"),
        ("US - International (QWERTY)", "us_international", "keymap"),
    ]
    lines = [HEADER, "const List<(String, Map<String, String>)> keymapTables = [\n"]
    for name, mod, attr in entries:
        if mod is None:
            lines.append("  (%s, <String, String>{}),\n" % ds(name))
            continue
        m = importlib.import_module("keymap." + mod)
        table = getattr(m, attr)
        lines.append("  (%s, {\n" % ds(name))
        for k, v in table.items():
            lines.append("    %s: %s,\n" % (ds(k), ds(v)))
        lines.append("  }),\n")
    lines.append("];\n")
    with open(os.path.join(OUT, "keymaps", "keymap_tables.dart"), "w") as f:
        f.write("".join(lines))


def gen_display_defs():
    import importlib
    m = importlib.import_module("widgets.display_keyboard_defs")
    names = ["ansi_100", "ansi_80", "ansi_70", "iso_100", "iso_80", "iso_70",
             "mods", "mods_narrow"]
    lines = [HEADER]
    for n in names:
        camel = n.split("_")[0] + "".join(p.title() for p in n.split("_")[1:])
        lines.append("const String displayDef%s = %s;\n\n" % (
            camel[0].upper() + camel[1:], ds(getattr(m, n).strip())))
    with open(os.path.join(OUT, "ui", "display_keyboard_defs.dart"), "w") as f:
        f.write("".join(lines))


def gen_qmk_settings():
    with open(os.path.join(SRC, "..", "resources", "base", "qmk_settings.json")) as f:
        data = f.read()
    with open(os.path.join(OUT, "settings", "qmk_settings_json.dart"), "w") as f:
        f.write(HEADER + "const String qmkSettingsJson = r'''\n" + data + "\n''';\n")



def dart_kc(k):
    args = [ds(k.qmk_id), ds(k.label)]
    if k.tooltip is not None:
        args.append("tooltip: %s" % ds(k.tooltip))
    if k.masked:
        args.append("masked: true")
    if k.printable is not None:
        args.append("printable: %s" % ds(k.printable))
    extra_alias = k.alias[1:]
    if extra_alias:
        args.append("alias: [%s]" % ", ".join(ds(a) for a in extra_alias))
    rec = [a for a, kc in Keycode.recorder_alias_to_keycode.items() if kc is k]
    if rec:
        args.append("recorderAlias: [%s]" % ", ".join(ds(a) for a in rec))
    if k.requires_feature is not None:
        args.append("requiresFeature: %s" % ds(k.requires_feature))
    return "Keycode(%s)" % ", ".join(args)


def gen_keycode_defs():
    global Keycode
    from keycodes import keycodes as m
    Keycode = m.Keycode
    lists = [
        ("KEYCODES_SPECIAL", "keycodesSpecial"),
        ("KEYCODES_BASIC", "keycodesBasic"),
        ("KEYCODES_BASIC_NUMPAD", "keycodesBasicNumpad"),
        ("KEYCODES_BASIC_NAV", "keycodesBasicNav"),
        ("KEYCODES_SHIFTED", "keycodesShifted"),
        ("KEYCODES_ISO", "keycodesIso"),
        ("KEYCODES_ISO_KR", "keycodesIsoKr"),
        ("KEYCODES_BOOT", "keycodesBoot"),
        ("KEYCODES_MODIFIERS", "keycodesModifiers"),
        ("KEYCODES_QUANTUM", "keycodesQuantum"),
        ("KEYCODES_BACKLIGHT", "keycodesBacklight"),
        ("KEYCODES_MEDIA", "keycodesMedia"),
        ("KEYCODES_MACRO_BASE", "keycodesMacroBase"),
        ("KEYCODES_MIDI_BASIC", "keycodesMidiBasic"),
        ("KEYCODES_MIDI_ADVANCED", "keycodesMidiAdvanced"),
    ]
    lines = [HEADER, "import 'keycode.dart';\n\n"]
    # BASIC already contains NUMPAD and NAV (extended in the Python source);
    # emit the sub-lists as views on the shared instances so registration
    # happens once.
    basic = m.KEYCODES_BASIC
    numpad_start = len(basic) - len(m.KEYCODES_BASIC_NUMPAD) - len(m.KEYCODES_BASIC_NAV)
    nav_start = len(basic) - len(m.KEYCODES_BASIC_NAV)
    iso_kr_start = len(m.KEYCODES_ISO) - len(m.KEYCODES_ISO_KR)
    for pyname, dartname in lists:
        if pyname == "KEYCODES_BASIC_NUMPAD":
            lines.append("final List<Keycode> %s = keycodesBasic.sublist(%d, %d);\n\n" % (dartname, numpad_start, nav_start))
            continue
        if pyname == "KEYCODES_BASIC_NAV":
            lines.append("final List<Keycode> %s = keycodesBasic.sublist(%d);\n\n" % (dartname, nav_start))
            continue
        if pyname == "KEYCODES_ISO_KR":
            lines.append("final List<Keycode> %s = keycodesIso.sublist(%d);\n\n" % (dartname, iso_kr_start))
            continue
        lines.append("final List<Keycode> %s = [\n" % dartname)
        for k in getattr(m, pyname):
            lines.append("  %s,\n" % dart_kc(k))
        lines.append("];\n\n")
    with open(os.path.join(OUT, "keycodes", "keycode_defs.dart"), "w") as f:
        f.write("".join(lines))


gen_kc("keycodes_v5", "keycodes_v5.dart", "v5")
gen_kc("keycodes_v6", "keycodes_v6.dart", "v6")
gen_keymaps()
gen_display_defs()
gen_qmk_settings()
gen_keycode_defs()
print("ok")
